apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-develop
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: demo-product
spec:
  project: default
  destination:
    name: in-cluster
    namespace: develop
  source:
    path: develop
    repoURL: https://github.com/mihuross/demo-app
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
